apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
spec:
  ports:
  - name: web
    port: 8080
  selector:
    app.kubernetes.io/name: ingress-nginx
